---
- name: change redpanda configuration
  gather_facts: no
  become: yes
  hosts: redpanda
  remote_user: fedora
  tasks:
  - name: change-config-file
    blockinfile:
      path: /etc/redpanda/redpanda.yaml
      insertafter: "redpanda:"
      marker: "# {mark} REDPANDA PARAMS BLOCK"
      block: |2
          log_compaction_interval_ms: 36000000
          group_topic_partitions: 1
