---
- name: deploy-cluster
  become: yes
  hosts: redpanda
  gather_facts: no
  remote_user: fedora
  tasks:
    - name: dnf install deps
      dnf:
        name: iotop,sysstat,psmisc,telnet,perf,htop,iftop
        state: installed
    - name: iperf
      yum:
        name: https://iperf.fr/download/fedora/iperf3-3.1.3-1.fc24.i686.rpm
        state: installed