---

- name: kafka producer
  gather_facts: no 
  hosts: "{{ groups['redpanda'][1] }}"
  vars:
    user: "{{hostvars[inventory_hostname].ansible_user}}"
    topic: 'zenly-test'
    partitions: 1024
    rf: 3
  tasks:
  - name: create topic
    become_user: "{{user}}"
    shell:
      cmd: | 
          rpk api topic create\
            {{topic}}-{{item}} \
            -p {{partitions}} \
            -r {{rf}} \
            --compact
    with_items:
    - 1
    - 2
    - 3
    - 4
    - 5
