---    
- name: consumer
  hosts: "{{ groups['redpanda'][::2] }}"  
  gather_facts: no
  vars:
    user: "{{hostvars[inventory_hostname].ansible_user}}"
    topic: 'sfo'
    record_count: 9223372036854775800
    consumer_group: 'test-group-2'
  tasks:
  - name: create consumer service
    copy:
      dest: /lib/systemd/system/kafka-consumer.service
      content: |
        [Unit]
        Description=Kafka consumer
        After=redpanda.service
        Requires=local-fs.target network-online.target
        
        [Service]
        PermissionsStartOnly=true
        Type=simple
        ExecStart=/opt/kafka-dev/bin/kafka-run-class.sh kafka.tools.ConsumerPerformance \
            --broker-list "{{ansible_play_batch | map('extract', hostvars, ['private_ip']) |join(':9092,')}}:9092" \
            --topic "{{topic}}" \
            --group "{{consumer_group}}" \
            --show-detailed-stats \
            --messages {{record_count}} \
            --timeout 2147483647000
        TimeoutStartSec=900
        TimeoutStopSec=11s
        KillMode=process
        Restart=always
        User=redpanda
        OOMScoreAdjust=-950
        StandardOutput=syslog
        StandardError=syslog
        SyslogLevelPrefix=false
        AmbientCapabilities=CAP_SYS_NICE
        
        [Install]
        WantedBy=multi-user.target
  - name: restart systemd
    systemd:
      daemon_reload: yes
  - name: start consumer
    systemd:
      name: kafka-consumer
      enabled: true
      state: stopped